//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportFrom
    {
        public int OutputMaterialId { get; set; }
        public int InputbillId { get; set; }
        public int ExportFromQuantity { get; set; }
    
        public virtual InputBill InputBill { get; set; }
        public virtual OutputMaterial OutputMaterial { get; set; }
    }
}
