//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestInfo
    {
        public int GuestInfoId { get; set; }
        public string GuestInfoName { get; set; }
        public string GuestInfoPhone { get; set; }
        public string GuestInfoAddress { get; set; }
        public string GuestInfoEmail { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
