//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputBill
    {
        public InputBill()
        {
            this.ExportFroms = new HashSet<ExportFrom>();
            this.InputMaterials = new HashSet<InputMaterial>();
        }
    
        public int InputBillId { get; set; }
        public string InputBillCode { get; set; }
        public int InputBillAmount { get; set; }
        public string InputRawImage { get; set; }
        public int InputTaxAmount { get; set; }
        public int SupplierId { get; set; }
        public System.DateTime ImportDate { get; set; }
    
        public virtual ICollection<ExportFrom> ExportFroms { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<InputMaterial> InputMaterials { get; set; }
    }
}
