//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherExpense
    {
        public int OtherExpenseId { get; set; }
        public string OtherExpenseName { get; set; }
        public int OtherExpenseAmount { get; set; }
        public Nullable<int> OtherExpenseMonthTime { get; set; }
        public Nullable<int> OtherExpenseYearTime { get; set; }
        public int Type { get; set; }
    }
}
