//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputMaterial
    {
        public OutputMaterial()
        {
            this.ExportFroms = new HashSet<ExportFrom>();
        }
    
        public int OutputMaterialId { get; set; }
        public int ExportQuantity { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string OutputMaterialNote { get; set; }
        public int ProductMaterialId { get; set; }
        public int OrderItemId { get; set; }
    
        public virtual ICollection<ExportFrom> ExportFroms { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        public virtual ProductMaterial ProductMaterial { get; set; }
    }
}
