//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterial
    {
        public ProductMaterial()
        {
            this.InputMaterials = new HashSet<InputMaterial>();
            this.OutputMaterials = new HashSet<OutputMaterial>();
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int ProductMaterialId { get; set; }
        public string ProductMaterialName { get; set; }
        public string ProductMaterialUnit { get; set; }
        public int CurrentQuantity { get; set; }
        public Nullable<int> StandardQuantity { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<InputMaterial> InputMaterials { get; set; }
        public virtual ICollection<OutputMaterial> OutputMaterials { get; set; }
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
