//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int ProductId { get; set; }
        public int ProductMaterialId { get; set; }
        public double Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductMaterial ProductMaterial { get; set; }
    }
}
