//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxType
    {
        public TaxType()
        {
            this.TaxRate = new HashSet<TaxRate>();
        }
    
        public int TaxTypeID { get; set; }
        public string TaxTypeName { get; set; }
        public string Method { get; set; }
        public string Condition { get; set; }
        public string Abbreviation { get; set; }
    
        public virtual ICollection<TaxRate> TaxRate { get; set; }
    }
}
