//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TndnTaxDeclaration
    {
        public int TndnTaxDeclarationId { get; set; }
        public int Year { get; set; }
        public Nullable<int> MaxRevenueRatio { get; set; }
        public string TaxAgentOwnerName { get; set; }
        public string TaxAgentName { get; set; }
        public string TaxAgentNo { get; set; }
        public string TaxAgentTaxCode { get; set; }
        public string TaxAgentAddress { get; set; }
        public string TaxAgentDistrict { get; set; }
        public string TaxAgentProvince { get; set; }
        public string TaxAgentPhone { get; set; }
        public string TaxAgentFax { get; set; }
        public string TaxAgentEmail { get; set; }
        public string SignName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Value22No { get; set; }
        public Nullable<System.DateTime> Value22Date { get; set; }
        public Nullable<int> ValueA1 { get; set; }
        public Nullable<int> ValueB1 { get; set; }
        public Nullable<int> ValueB2 { get; set; }
        public Nullable<int> ValueB3 { get; set; }
        public Nullable<int> ValueB4 { get; set; }
        public Nullable<int> ValueB5 { get; set; }
        public Nullable<int> ValueB6 { get; set; }
        public Nullable<int> ValueB7 { get; set; }
        public Nullable<int> ValueB8 { get; set; }
        public Nullable<int> ValueB9 { get; set; }
        public Nullable<int> ValueB10 { get; set; }
        public Nullable<int> ValueB11 { get; set; }
        public Nullable<int> ValueB12 { get; set; }
        public Nullable<int> ValueB13 { get; set; }
        public Nullable<int> ValueB14 { get; set; }
        public Nullable<int> ValueC1 { get; set; }
        public Nullable<int> ValueC2 { get; set; }
        public Nullable<int> ValueC3 { get; set; }
        public Nullable<int> ValueC3a { get; set; }
        public Nullable<int> ValueC3b { get; set; }
        public Nullable<int> ValueC4 { get; set; }
        public Nullable<int> ValueC5 { get; set; }
        public Nullable<int> ValueC6 { get; set; }
        public Nullable<int> ValueC7 { get; set; }
        public Nullable<int> ValueC8 { get; set; }
        public Nullable<int> ValueC9 { get; set; }
        public Nullable<int> ValueC9a { get; set; }
        public Nullable<int> ValueC10 { get; set; }
        public Nullable<int> ValueC11 { get; set; }
        public Nullable<int> ValueC12 { get; set; }
        public Nullable<int> ValueC13 { get; set; }
        public Nullable<int> ValueC14 { get; set; }
        public Nullable<int> ValueC15 { get; set; }
        public Nullable<int> ValueC16 { get; set; }
        public Nullable<int> ValueD { get; set; }
        public Nullable<int> ValueD1 { get; set; }
        public Nullable<int> ValueD2 { get; set; }
        public Nullable<int> ValueD3 { get; set; }
        public Nullable<int> ValueE { get; set; }
        public Nullable<int> ValueE1 { get; set; }
        public Nullable<int> ValueE2 { get; set; }
        public Nullable<int> ValueE3 { get; set; }
        public Nullable<int> ValueG { get; set; }
        public Nullable<int> ValueG1 { get; set; }
        public Nullable<int> ValueG2 { get; set; }
        public Nullable<int> ValueG3 { get; set; }
        public Nullable<int> ValueH { get; set; }
        public Nullable<int> ValueI { get; set; }
        public Nullable<bool> ValueL1 { get; set; }
        public Nullable<int> ValueL2No { get; set; }
        public Nullable<System.DateTime> ValueL3 { get; set; }
        public Nullable<int> ValueL4 { get; set; }
        public Nullable<int> ValueL5 { get; set; }
        public Nullable<System.DateTime> ValueM1FromDate { get; set; }
        public Nullable<System.DateTime> ValueM1ToDate { get; set; }
        public Nullable<int> ValueM2 { get; set; }
        public Nullable<int> Value1 { get; set; }
        public Nullable<int> Value2 { get; set; }
        public Nullable<int> Value3 { get; set; }
        public Nullable<int> Value4 { get; set; }
        public Nullable<int> Value5 { get; set; }
        public Nullable<int> Value6 { get; set; }
        public Nullable<int> Value7 { get; set; }
        public Nullable<int> Value8 { get; set; }
        public Nullable<int> Value9 { get; set; }
        public Nullable<int> Value10 { get; set; }
        public Nullable<int> Value11 { get; set; }
        public Nullable<int> Value12 { get; set; }
        public Nullable<int> Value13 { get; set; }
        public Nullable<int> Value14 { get; set; }
        public Nullable<int> Value15 { get; set; }
        public Nullable<int> Value16 { get; set; }
        public Nullable<int> Value17 { get; set; }
        public Nullable<int> Value18 { get; set; }
        public Nullable<int> Value19 { get; set; }
        public string StoreOwnerName { get; set; }
        public string StoreTaxCode { get; set; }
        public string StoreAddress { get; set; }
        public string StoreDistrict { get; set; }
        public string StoreProvince { get; set; }
        public string StorePhone { get; set; }
        public string StoreFax { get; set; }
        public string StoreEmail { get; set; }
    }
}
