//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTaxDeclaration
    {
        public int VatTaxDeclarationId { get; set; }
        public int Quarter { get; set; }
        public int Year { get; set; }
        public string TaxAgentOwnerName { get; set; }
        public string TaxAgentTaxCode { get; set; }
        public string TaxAgentName { get; set; }
        public string TaxAgentNo { get; set; }
        public string InputCategory1 { get; set; }
        public Nullable<int> InputCategory1TotalAmount { get; set; }
        public Nullable<int> InputCategory1TotalTaxAmount { get; set; }
        public string InputCategory2 { get; set; }
        public Nullable<int> InputCategory2TotalAmount { get; set; }
        public Nullable<int> InputCategory2TotalTaxAmount { get; set; }
        public string InputCategory3 { get; set; }
        public Nullable<int> InputCategory3TotalAmount { get; set; }
        public Nullable<int> InputCategory3TotalTaxAmount { get; set; }
        public int InputTotalAmountValue23 { get; set; }
        public int InputTotalTaxAmountValue24 { get; set; }
        public string CreateLocation { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string SignName { get; set; }
        public string OutputCategory1 { get; set; }
        public string OutputCategory2 { get; set; }
        public string OutputCategory3 { get; set; }
        public string OutputCategory4 { get; set; }
        public Nullable<int> OutputCategory1TotalAmountValue26 { get; set; }
        public Nullable<int> OutputCategory2TotalAmountValue29 { get; set; }
        public Nullable<int> OutputCategory3TotalAmountValue30 { get; set; }
        public Nullable<int> OutputCategory4TotalAmountValue32 { get; set; }
        public Nullable<int> OutputCategory3TotalTaxAmountValue31 { get; set; }
        public Nullable<int> OutputCategory4TotalTaxAmountValue33 { get; set; }
        public int OutputTotalAmountValue34 { get; set; }
        public int HaveTaxOutputTotalAmountValue27 { get; set; }
        public int OutputTotalTaxAmountValue28 { get; set; }
        public string Value20No { get; set; }
        public Nullable<System.DateTime> Value20Date { get; set; }
        public Nullable<int> Value21 { get; set; }
        public Nullable<int> Value22 { get; set; }
        public Nullable<int> Value25 { get; set; }
        public Nullable<int> Value36 { get; set; }
        public Nullable<int> Value37 { get; set; }
        public Nullable<int> Value38 { get; set; }
        public Nullable<int> Value39 { get; set; }
        public Nullable<int> Value40a { get; set; }
        public Nullable<int> Value40b { get; set; }
        public Nullable<int> Value41 { get; set; }
        public Nullable<int> Value43 { get; set; }
        public string TaxAgentAddress { get; set; }
        public string TaxAgentDistrict { get; set; }
        public string TaxAgentProvince { get; set; }
        public string TaxAgentPhone { get; set; }
        public string TaxAgentFax { get; set; }
        public string TaxAgentEmail { get; set; }
        public Nullable<int> Value40 { get; set; }
        public Nullable<int> Value42 { get; set; }
        public string StoreOwnerName { get; set; }
        public string StoreTaxCode { get; set; }
        public string StoreAddress { get; set; }
        public string StoreDistrict { get; set; }
        public string StoreProvince { get; set; }
        public string StorePhone { get; set; }
        public string StoreFax { get; set; }
        public string StoreEmail { get; set; }
    }
}
